language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: KtjgztEk1PwlBnslksHcqyvsT9OBdFLk4NisoSrpxsHR0xJbC2NPsSQ4K/vmeu9iqwJ289QsWIByi8T5eyYf+cezbpWu5cLxoK8MWJtiJABhoiYu7+ndmAmhkP7rbgu38HItG718ZKyNKl5A3PJmnagbYWdAyq3B87IqSMG64IkBh+quoN6VUEZtNGPmzc9mxNY82GFmwIvE957mYRPRU1Od2VR1H9BRbQo7lG6gv87sA7zaeQHP6l7p1fxaXrHiBnh1w3uANtNfGLyDuw6feBOVpXQNsqEXVWrdY5mITTq/dr1K0W/kKSAyBC77XMXkmON2ypequsOeQE53tKLUiFPNu7JPu+WuBnLs3Szth8ywLf0WNjnnHUxgtbBVRDUPUNpDAFFD87P0NNSDwTFFlsGdubs+NYeB50KHCnzjd8BqocfXFP1GCnwSDdZDps78Lcx68AIV8g2J6JZgsdCnooXzbVN1CdKKczz9zjoUfQNX/tXMciXETh+VNbGsUK/AwDQ/vXhyQMvMY+F4rik6uFPEuMXNkqPZ63Dr6HCCppp2Fh39RlqCPLbRzc58fUQPM6rTsOHQuobUJIMLZDpc/C9Ikg9h/GUSXtvSOd60woKLmUUy1fJ0D8Dved2Vfh4d+Mqz7Svb2YdTbzgufNeGHvOEDzu3hWmw6QhRvkrinEk=
  - secure: lN+0f1IOmw4TtibrAie9vAR4dv3L29nwxMKKIubPAgz2N/uk+TzXoY4blg4+dcD98hB7S77CKBihPwtdWed4GdNMsSLydnjXeRqNJfCPAeEQaXAe7l/yFxGc+MQlewqmndy2LBQpXqtg2IRqkfxZBQsVEV60YJO6E7ijGSBze7rJuqXVASeN1yK10VhRhESYTUupxsZoH61yrch6I1qYj9d3FxLiRBqYdv+yLh41gl8BOglC3Jn8hKEbh/yrjzDe3pZ4PRp1zp11Se1AZk36YmP3gu1pQEOs8WN9Re92P0Gu2nlIXLLxyvJiKD12x58e9T3qyPTgALGeuVajsJqrDvMYnBXcLI8XO4kxxUDCid13ktGS1oKjMTEe7JwjyNveBIkmBMCG1RTocbuTfuypxm5WCzVzfcI/aD5zlCecKScjQO+45K+t8VN4Lah31o4ngRMs5Nm1VT1OnhMuhARz+Y5eOLF4rbdPzPHw3qx754GDVokTKtQSCM0GikPGxqBDgxPPwoxr7TInViZLw8DmbdTCDWeO73meGg5DU4m0YQ22tftVS6QNSkrQzPPPyJVQ9AU7EOuNu4g7rAYAPijCZxyJttAvFXs+0UJe151OcHyTD7MfqAKfPI2RSBJ5DQfsuymSpsU5Q/MXUuwP5rVHqgmadG9pp5OB8O71FJLay0Y=
